# parent ID (60.2 ms)
SELECT DISTINCT C1.CUI AS 'CHILD_CUI', MRREL.CUI2 AS 'PAR_CUI'
	FROM MRCONSO AS C1
	INNER JOIN MRREL ON MRREL.CUI1 = C1.CUI
	INNER JOIN MRCONSO C2 ON C2.CUI = MRREL.CUI2
	WHERE C1.CUI IN ('C0069515', 'C0008659')
	AND (MRREL.RELA='inverse_isa'
	OR MRREL.REL = 'PAR'
	OR MRREL.REL = 'RB');

# child string (1.9 ms)
SELECT C2.CUI AS 'CHILD_CUI', C2.STR AS 'CHILD_STR', MAX(R2.RANK) AS 'MAXRANK'
FROM MRCONSO AS C2 
INNER JOIN MRRANK AS R2 ON (C2.SAB = R2.SAB AND C2.TTY = R2.TTY)
WHERE C2.CUI IN ('C0069515', 'C0008659')
AND C2.STT = 'PF'
AND C2.ISPREF = 'Y'
GROUP BY C2.CUI;

# child string and parent ID (3.8 ms)
SELECT C1.CUI AS 'CHILD_CUI', C1.STR AS 'STR', MRREL.CUI2 AS 'PAR_CUI'
	FROM (SELECT C2.CUI, MAX(R2.RANK) AS MAXRANK
		FROM MRCONSO AS C2 
		INNER JOIN MRRANK AS R2 ON (C2.SAB = R2.SAB AND C2.TTY = R2.TTY)
		WHERE C2.CUI IN ('C0069515', 'C0008659')
		GROUP BY C2.CUI) AS T 
	INNER JOIN MRRANK R1 ON R1.RANK = T.MAXRANK
	INNER JOIN MRCONSO C1 ON (C1.SAB = R1.SAB AND C1.TTY = R1.TTY)
	INNER JOIN MRREL ON MRREL.CUI1 = C1.CUI
	WHERE C1.CUI = T.CUI
	AND (MRREL.RELA='inverse_isa'
	OR MRREL.REL = 'PAR'
	OR MRREL.REL = 'RB');

# parent IDs x2 (384 ms)
SELECT DISTINCT C1.CUI AS 'Child CUI', P1.CUI AS 'Parent1 CUI', M2.CUI2 AS 'Parent2 CUI'
FROM MRCONSO C1
INNER JOIN MRREL M1 ON M1.CUI1 = C1.CUI
  AND (M1.RELA='inverse_isa'
  OR M1.REL IN ('PAR','RB'))
INNER JOIN MRCONSO P1 ON P1.CUI = M1.CUI2
INNER JOIN MRREL M2 ON M2.CUI1 = P1.CUI
  AND (M2.RELA='inverse_isa'
  OR M2.REL IN ('PAR','RB'))
WHERE C1.CUI = 'C0069515';

# parent IDs x2 and parent string x1 (115 s)
SELECT C1.CUI AS 'Child CUI', C1.STR AS 'Child name', P1.CUI AS 'Parent1 CUI', P1.Str AS 'Parent1 name', M2.CUI2 AS 'Parent2 CUI'
FROM (SELECT C2.CUI, MAX(R2.RANK) AS MAXRANK
  FROM MRCONSO AS C2 INNER JOIN MRRANK AS R2 ON (C2.SAB = R2.SAB AND C2.TTY = R2.TTY)
  WHERE C2.CUI IN ('C0069515', 'C0008659')
  GROUP BY C2.CUI) AS T1
  
INNER JOIN MRRANK R1 ON R1.RANK = T1.MAXRANK
INNER JOIN MRCONSO C1 ON (C1.SAB = R1.SAB AND C1.TTY = R1.TTY AND C1.CUI = T1.CUI)
INNER JOIN MRREL M1 ON M1.CUI1 = C1.CUI

INNER JOIN (SELECT C3.CUI, MAX(R3.RANK) AS MAXRANK
  FROM MRCONSO AS C3 
  INNER JOIN MRRANK AS R3 ON (C3.SAB = R3.SAB AND C3.TTY = R3.TTY)
  GROUP BY C3.CUI) AS T2 ON T2.CUI = M1.CUI2

INNER JOIN MRRANK R2 ON R2.RANK = T2.MAXRANK
INNER JOIN MRCONSO P1 ON (P1.SAB = R2.SAB AND P1.TTY = R2.TTY AND P1.CUI = T2.CUI)
INNER JOIN MRREL M2 ON (M2.CUI1 = P1.CUI AND M2.CUI1 = M1.CUI2)

WHERE (M1.RELA='inverse_isa'
OR M1.REL = 'PAR'
OR M1.REL = 'RB')
AND (M2.RELA='inverse_isa'
OR M2.REL = 'PAR'
OR M2.REL = 'RB');
