SELECT C1.CUI AS 'Child CUI', C1.STR AS 'Term name', MRREL.CUI2 AS 'Parent CUI'
FROM (SELECT C2.CUI, MAX(R2.RANK) AS MAXRANK
FROM MRCONSO AS C2 INNER JOIN MRRANK AS R2 ON (C2.SAB = R2.SAB AND C2.TTY = R2.TTY)
WHERE C2.CUI IN ('C0069515', 'C0008659')
GROUP BY C2.CUI) AS T INNER JOIN MRRANK R1 ON R1.RANK = T.MAXRANK
INNER JOIN MRCONSO C1 ON (C1.SAB = R1.SAB AND C1.TTY = R1.TTY)
INNER JOIN MRREL ON MRREL.CUI1 = C1.CUI
WHERE C1.CUI = T.CUI
AND (MRREL.RELA='inverse_isa'
OR MRREL.REL = 'PAR'
OR MRREL.REL = 'RB');